apiVersion: v1
kind: Namespace
metadata:
  name: crater-baiter
---
apiVersion: v1
kind: Secret
metadata:
  name: crater-baiter-secrets
  namespace: crater-baiter
type: Opaque
data:
  DISCORD_CLIENT_ID: MTA3MjIwOTMxNzc3NzkwNzgxMw==
  DISCORD_SECRET_KEY: WW5PREdjclBpSV8tRzhNREpPQ1ZfbDBlVnVYekdldmY=
  SECRET_KEY: M2JkNDEyYjI0OGU4NDEzOWE1M2M0NzU0YzEwMDY1ZDI=
  CONFIG_APP: cHJvZA==
  HOST: ZGFsYXJhbi5iZW5nYW4uZGV2
  SQLALCHEMY_DATABASE_URI: cG9zdGdyZXNxbDovL2FwcF9ydW5uZXI6U2tOeU01YUU4ZEVhWlQyVXhuWjlrYzhkckx3MmE1dXlAYnViYmxlYm95OjU0MzIvY3JhdGVyX2JhaXRlcg==
  # postgresql://app_runner:SkNyM5aE8dEaZT2UxnZ9kc8drLw2a5uy@bubbleboy:5432/crater_baiter
