apiVersion: v1
kind: Namespace
metadata:
  name: crater-baiter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crater-baiter
  namespace: crater-baiter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crater-baiter
  template:
    metadata:
      labels:
        app: crater-baiter
    spec:
      containers:
        - name: crater-baiter
          image: bengan/crater-baiter:0.2.4
          ports:
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: crater-baiter-secrets
          resources:
            limits:
              cpu: "0.25"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: crater-baiter
  namespace: crater-baiter
spec:
  type: ClusterIP
  selector:
    app: crater-baiter
  ports:
    - name: http
      port: 5001
      targetPort: 5001