apiVersion: v1
kind: Secret
metadata:
  name: crater-baiter-secrets
  namespace: crater-baiter
type: Opaque
data:
  # base64 encode your value e.g by running echo -n YOUR_STRING | base64
  DISCORD_CLIENT_ID: <base64 encoded value of your discord client id>
  DISCORD_SECRET_KEY: <base64 encoded value of your discord secret key>
  SECRET_KEY: <base64 encoded value of your secret key>
  APP_CONFIG: <base64 encoded value of config dev, docker, prod>
  HOST: <base64 encoded value of your host adress, e.g dalaran.example.com>